language: node_js

node_js:
  - '8'
  - '10'
  - '11'

cache:
  directories:
    - ~/.npm

git:
  depth: 5

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

before_install:
  - openssl aes-256-cbc -K $encrypted_78a1249b0419_key -iv $encrypted_78a1249b0419_iv
    -in .env.enc -out .env -d

# Retry install on fail to avoid failing a build on network/disk/external errors
install:
  - travis_retry npm i

script:
  - npm run lint
  - npm run coverage:all
  - commitlint-travis

after_success: npm run coveralls
