name: bump-version

on:
  # you can set the `bump-version` label
  pull_request:
    branches:
      - master
    types:
      - labeled
  # or write a `/bump` comment
  issue_comment:
    types:
      - created

jobs:
  bump-version:
    if: ${{ github.event.pull_request && (github.event.action == 'labeled' && github.event.label.name == 'bump-version') || (github.event_name == 'issue_comment' && github.event.comment.author_association == 'MEMBER' && contains(github.event.comment.body, '/bump')) }}
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          repository: goparrot/.github
          event-type: ${{ github.workflow }}
          client-payload: '{"origin_github": ${{ toJson(github) }}}'
