name: CD

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to NPM
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org

      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run coverage:all
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          MAP_QUEST_API_KEY: ${{ secrets.MAP_QUEST_API_KEY }}
          HERE_APP_ID: ${{ secrets.HERE_APP_ID }}
          HERE_APP_CODE: ${{ secrets.HERE_APP_CODE }}

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dist and publish to npm
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          GITHUB_TOKEN: ${{ secrets.CONVENTIONAL_GITHUB_RELEASER_TOKEN }}
